config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sections#index'
  resources :categories
  resources :topics do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :section
  has_many :topics
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates :message, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :categories
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.new(post_params)

    @post.user_id = current_user.id

    if @post.save
      redirect_to @topic
    else
      render :new
    end

  end

  private

  def post_params
    params.require(:post).permit(:message)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
    @topic.posts.build
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.views = 0

    if @topic.save
      @post = @topic.posts.new(post_params)
      @post.user_id = current_user.id

      if @post.save
        redirect_to @topic
      else
        @topic.destroy
        render :new
      end
    else
      render :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @topic.views += 1
    @topic.save
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :category_id, :pinned, :closed)
  end

  def post_params
    params.require(:topic).require(:posts).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/categories/show.html.erb
<h1>Category <%= @category.name %></h1>

<%= link_to 'New topic', new_topic_path, style: 'font-size: 25px'  %>

<p>Category topics:</p>
<hr>
<table>
  <tr>
    <th>Topic</th>
    <th>Author</th>
    <th>Views</th>
    <th>Posts</th>
    <th>Status</th>
    <th>Creation time</th>
  </tr>
<% @category.topics.each do |topic| %>
  <tr>
    <td><a style="color: red" href="<%= topic_path(topic) %>"><%= topic.title %></a></td>
    <td><%= topic.user.username %></td>
    <td><%= topic.views > 0 ? topic.views : '-' %></td>
    <td><%= topic.posts.count > 0 ? topic.posts.count : '-' %></td>
    <td><%= '🖈' if topic.pinned %> <%= '🔒' if topic.closed %></td>
    <td><%= topic.created_at %></td>
  </tr>
<% end %>
</table>

app/views/layouts/_header.html.erb
<header>
  <%= stylesheet_link_tag "header" %>
  <ul class="nav-list">
    <li>
      <%= link_to 'Forum', root_path, class: 'header-link' %>
    </li>

    <% if user_signed_in? %>
      <li>
      <%= link_to current_user.username, edit_user_registration_path, class: 'header-link' %>
      </li>

      <li>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'header-link' %> |
      </li>
    <% else %>
      <li>
        <div>
        <%= link_to 'Sign up', new_user_registration_path, class: 'header-link' %>
        </div>
      </li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/sections/index.html.erb
<h1 class="page-title">My forum</h1><br><br>
<p>Forum sections:</p>
<hr>
<% @sections.each do |section| %>
  <p><%= section.name %></p>
  <% section.categories.each do |category| %>
    <a style="color: #ff0000; margin-left: 15px" href="<%= category_path(category) %>"><%= category.name %></a>
    <p style="margin-left: 30px; font-size: 12px; color: gray"><%= category.description %></p>
  <% end %>
  <hr>
<% end %>

app/views/topics/new.html.erb
<h1>Create new topic</h1>

<%= form_with model: @topic do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :category %><br>
    <%= form.grouped_collection_select(:category_id, Section.all, :categories, :name, :id, :name) %>
  </p>

  <p>
    <%= form.label :pinned %>
    <%= form.check_box :pinned %>
  </p>

  <p>
    <%= form.label :closed %>
    <%= form.check_box :closed %>
  </p>

  <%= form.fields_for :posts do |post| %>
  <p>
    <%= post.label :message %><br>
    <%= post.text_area :message %>
  </p>
  <% end %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<hr>

<table>
  <tr>
    <th>#</th>
    <th>Author</th>
    <th>Message</th>
  </tr>
<% @topic.posts.each_with_index do |post, index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= post.user.username %></td>
    <td><%= post.message %></td>
  </tr>
<% end %>
</table>
<hr>
<% if user_signed_in? %>
  <p>Make a post:</p>
  <%= form_with model: [ @topic, @topic.posts.build ] do |form| %>
    <p>
      <%= form.label :message %>
      <%= form.text_area :message %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
<% else %>
  <%= link_to 'Sign in to make a post in the topic!', new_user_session_path %>
<% end %>